### ISSUE TITLE
File doesn't exist

### ISSUE THREAD

**Issue by qwertyuiopppp** [OleehyO/TexTeller#90]
Loading model and tokenizer...
Model and tokenizer loaded.
Inference...
-----------  Model Configuration -----------
Model Arch: DETR
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "/home/zjm/TexTeller/src/inference.py", line 62, in <module>
    latex_det_model = InferenceSession("./models/det_model/model/rtdetr_r50vd_6x_coco.onnx")
  File "/home/zjm/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/zjm/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ./models/det_model/model/rtdetr_r50vd_6x_coco.onnx failed:Load model ./models/det_model/model/rtdetr_r50vd_6x_coco.onnx failed. File doesn't exist

**Comment by qwertyuiopppp** [comment]
https://github.com/PaddlePaddle/PaddleDetection
