### ISSUE TITLE
启动ONNX就会报错

### ISSUE THREAD

**Issue by TUCYDAbc** [OleehyO/TexTeller#97]
不启动的话不会报错，但启动ONNX会立刻报错：
RuntimeError: Failed to import optimum.onnxruntime.modeling_seq2seq because of the following error (look up to see its traceback): Failed to import optimum.exporters.onnx.__main__ because of the following error (look up to see its traceback): Failed to import optimum.onnx.graph_transformations because of the following error (look up to see its traceback): DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。
Traceback:
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "D:\TexTeller3\TexTeller\src\web.py", line 157, in <module>
    texteller = get_texteller(use_onnx, accelerator)
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
File "D:\TexTeller3\TexTeller\src\web.py", line 54, in get_texteller
    return TexTeller.from_pretrained(os.environ['CHECKPOINT_DIR'], use_onnx=use_onnx, onnx_provider=accelerator)
File "D:\TexTeller3\TexTeller\src\models\ocr_model\model\TexTeller.py", line 34, in from_pretrained
    from optimum.onnxruntime import ORTModelForVision2Seq
File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1795, in _get_module
    raise RuntimeError(

尝试过更换python版本之类的操作，但没有作用，另一方面，我直接在python中运行import optimum.onnxruntime.modeling_seq2seq的语句是可以的，不清楚为什么会出错

**Comment by gk966988** [comment]
你的报错信息没贴完整，看着应该是环境问题，某个dll的问题

**Comment by TUCYDAbc** [comment]
CMD里的的报错信息：
2024-12-21 20:27:39.131 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1793, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\onnx\graph_transformations.py", line 19, in <module>
    import onnx
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1793, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\onnxruntime\modeling_seq2seq.py", line 44, in <module>
    from ..exporters.onnx import main_export
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\exporters\__init__.py", line 16, in <module>
    from .tasks import TasksManager  # noqa
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\exporters\tasks.py", line 173, in <module>
    class TasksManager:
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\exporters\tasks.py", line 338, in TasksManager
    "clip-text-model": supported_tasks_mapping(
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\exporters\tasks.py", line 117, in supported_tasks_mapping
    importlib.import_module(f"optimum.exporters.{backend}.model_configs"), config_cls_name
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\optimum\exporters\onnx\model_configs.py", line 23, in <module>
    from ...onnx import merge_decoders
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnx.graph_transformations because of the following error (look up to see its traceback):
DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\TexTeller3\TexTeller\src\web.py", line 157, in <module>
    texteller = get_texteller(use_onnx, accelerator)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "D:\TexTeller3\TexTeller\src\web.py", line 54, in get_texteller
    return TexTeller.from_pretrained(os.environ['CHECKPOINT_DIR'], use_onnx=use_onnx, onnx_provider=accelerator)
  File "D:\TexTeller3\TexTeller\src\models\ocr_model\model\TexTeller.py", line 34, in from_pretrained
    from optimum.onnxruntime import ORTModelForVision2Seq
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\TaD\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\transformers\utils\import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnxruntime.modeling_seq2seq because of the following error (look up to see its traceback):
Failed to import optimum.onnx.graph_transformations because of the following error (look up to see its traceback):
DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。
